"""
TRF fixture-based validation tests for the FIDE Dutch System Pairing Engine.

Reads pre-generated tournament TRF files (from tests/fixtures/) and validates
our Dutch engine by replaying each round:

1. Parse the TRF to extract players, round-by-round results, and pairings.
2. For each round, feed the engine the tournament state *before* that round.
3. Compare the engine's output against the known-correct pairings from the TRF.

This gives us ground-truth validation against thousands of tournament
configurations generated by a reference engine (JaVaFo/bbpPairings).

Fixtures cover:
- Small tournaments (7 players, 5 rounds) — bye edge cases
- Medium tournaments (9p/7r, 15p/9r) — forfeits, half-point byes, zero-point byes
- Large tournaments (30p/11r, 50p/15r, 50p/31r) — stress & many-byes/forfeits
- Misc edge cases from reference collections
"""

import os
import re
import unittest
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from caissify_pairings.engines.dutch import dutch_pairings

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# TRF16 Parser
# ---------------------------------------------------------------------------

def parse_trf(filepath: Path) -> dict:
    """
    Parse a TRF16 file into a structured dict.

    Returns:
        {
            "total_rounds": int,
            "num_players": int,
            "players": [
                {
                    "starting_number": int,
                    "name": str,
                    "rating": int,
                    "title_rating": int,
                    "rounds": [
                        {
                            "opponent_sn": int,  # 0 = no opponent (bye/absent)
                            "color": str,        # "w", "b", or "-"
                            "result": str,       # "1","0","=","H","U","Z","+","-","F"
                        },
                        ...
                    ],
                },
                ...
            ],
        }
    """
    text = filepath.read_text()
    lines = text.strip().split("\n")

    total_rounds = 0
    num_players = 0
    players = []

    for line in lines:
        if line.startswith("142"):
            total_rounds = int(line[4:].strip())
        elif line.startswith("062"):
            num_players = int(line[4:].strip())
        elif line.startswith("001"):
            player = _parse_player_line(line, total_rounds)
            if player:
                players.append(player)

    return {
        "total_rounds": total_rounds,
        "num_players": num_players,
        "players": players,
    }


def _parse_player_line(line: str, total_rounds: int) -> Optional[dict]:
    """
    Parse a single 001 player line from TRF16.

    Fixed-width format:
      Col 0-2:   "001"
      Col 4-7:   starting number (right-justified)
      Col 9:     sex
      Col 14-46: name (left-justified)
      Col 48-51: FIDE rating
      Col 53-55: federation
      Col 69-78: birth date
      Col 80-83: points
      Col 85-88: rank
      Col 91+:   round data (10 chars each)
    """
    if len(line) < 80:
        return None

    try:
        sn = int(line[4:8].strip())
    except (ValueError, IndexError):
        return None

    name = line[14:47].strip()

    try:
        rating = int(line[48:52].strip())
    except (ValueError, IndexError):
        rating = 0

    # Title rating (optional, col 53-56 area varies)
    # In these files, it appears after the FIDE rating
    try:
        title_rating = int(line[53:61].strip())
    except (ValueError, IndexError):
        title_rating = rating

    try:
        score = float(line[80:84].strip())
    except (ValueError, IndexError):
        score = 0.0

    # Parse round results starting at col 91
    rounds = []
    round_data = line[91:]
    for r in range(total_rounds):
        start = r * 10
        end = start + 10
        chunk = round_data[start:end] if start < len(round_data) else ""
        if len(chunk.strip()) == 0:
            rounds.append({"opponent_sn": 0, "color": "-", "result": "-"})
            continue

        # Format: "NNNN C R  " (4-char opponent, space, color, space, result, 2 spaces)
        try:
            opp_str = chunk[0:4].strip()
            opp_sn = int(opp_str) if opp_str and opp_str != "0000" else 0
        except (ValueError, IndexError):
            opp_sn = 0

        try:
            color = chunk[5].strip() if len(chunk) > 5 else "-"
        except IndexError:
            color = "-"

        try:
            result = chunk[7].strip() if len(chunk) > 7 else "-"
        except IndexError:
            result = "-"

        rounds.append({
            "opponent_sn": opp_sn,
            "color": color,
            "result": result,
        })

    return {
        "starting_number": sn,
        "name": name,
        "rating": rating,
        "title_rating": title_rating,
        "score": score,
        "rounds": rounds,
    }


def _result_to_points(result: str) -> float:
    """Convert TRF result code to points."""
    if result in ("1", "+"):
        return 1.0
    elif result in ("=",):
        return 0.5
    elif result in ("H", "P"):  # half-point bye, PAB
        return 0.5
    elif result in ("X",):
        return 0.5
    elif result in ("0", "-", "Z", "F"):
        return 0.0
    elif result in ("U", "W"):  # full-point bye
        return 1.0
    return 0.0


def _is_played_game(result: str) -> bool:
    """Check if this result represents an actual game (not a bye/forfeit/absent)."""
    return result in ("1", "0", "=")


def _is_bye(result: str) -> bool:
    """Check if this result is any kind of bye."""
    return result in ("H", "U", "Z", "F", "W", "P")


def _is_pairing_bye(result: str) -> bool:
    """Check if this result is a pairing-allocated bye (not voluntary)."""
    return result in ("U", "W")


def get_unavailable_players(trf_data: dict, round_num: int) -> Set[int]:
    """
    Get players who are unavailable for pairing in the given round.

    Players with voluntary byes (H=half-point, Z=zero-point) or who were
    absent/forfeited are not available for engine pairing.
    """
    unavailable = set()
    rnd_idx = round_num - 1
    for p in trf_data["players"]:
        sn = p["starting_number"]
        if rnd_idx >= len(p["rounds"]):
            continue
        rd = p["rounds"][rnd_idx]
        result = rd["result"]
        # Voluntary byes and zero-point byes mean the player was not available
        if result in ("H", "Z", "F"):
            unavailable.add(sn)
        # Forfeit loss with no opponent also means absent
        if result == "-" and rd["opponent_sn"] == 0:
            unavailable.add(sn)
    return unavailable


def build_round_state(trf_data: dict, up_to_round: int) -> Tuple[
    List[dict], Set[Tuple[int, int]], int
]:
    """
    Build the engine input state for pairing round `up_to_round + 1`.

    Replays rounds 1..up_to_round to accumulate:
    - Player scores and color history
    - Previous pairings set

    Returns:
        (players_list, previous_pairings, next_round_number)
    """
    players_by_sn = {}
    for p in trf_data["players"]:
        players_by_sn[p["starting_number"]] = {
            "id": p["starting_number"],
            "name": p["name"],
            "score": 0.0,
            "rating": p["rating"],
            "starting_number": p["starting_number"],
            "color_hist": [],
            "float_history": [],
            "bye_count": 0,
        }

    previous_pairings: Set[Tuple[int, int]] = set()

    for rnd_idx in range(up_to_round):
        for p in trf_data["players"]:
            sn = p["starting_number"]
            if rnd_idx >= len(p["rounds"]):
                continue
            rd = p["rounds"][rnd_idx]
            result = rd["result"]
            color = rd["color"]
            opp_sn = rd["opponent_sn"]

            # Accumulate score
            players_by_sn[sn]["score"] += _result_to_points(result)

            # Track color history (only for actual games and forfeit wins/losses)
            if color in ("w", "b"):
                if result not in ("H", "Z", "U", "W", "F", "P"):
                    players_by_sn[sn]["color_hist"].append(
                        "white" if color == "w" else "black"
                    )
                elif result in ("+", "-"):
                    # Forfeits still assign colors
                    players_by_sn[sn]["color_hist"].append(
                        "white" if color == "w" else "black"
                    )

            # Track byes
            if _is_bye(result):
                players_by_sn[sn]["bye_count"] += 1

            # Track previous pairings (actual games + forfeits)
            if opp_sn > 0 and result not in ("H", "Z", "U", "W", "F", "P"):
                pair = tuple(sorted([sn, opp_sn]))
                previous_pairings.add(pair)

    players = list(players_by_sn.values())
    return players, previous_pairings, up_to_round + 1


def extract_round_pairings(trf_data: dict, round_num: int) -> Set[Tuple[int, int]]:
    """
    Extract the known pairings for a specific round from the TRF data.

    Returns set of (min_sn, max_sn) for actual games,
    and (player_sn, 0) for byes.
    """
    pairings = set()
    seen = set()

    for p in trf_data["players"]:
        sn = p["starting_number"]
        if sn in seen:
            continue

        rnd_idx = round_num - 1
        if rnd_idx >= len(p["rounds"]):
            continue

        rd = p["rounds"][rnd_idx]
        opp_sn = rd["opponent_sn"]
        result = rd["result"]

        if opp_sn > 0 and result not in ("H", "Z", "U", "W", "F", "P"):
            pair = tuple(sorted([sn, opp_sn]))
            pairings.add(pair)
            seen.add(sn)
            seen.add(opp_sn)
        elif _is_pairing_bye(result):
            pairings.add((sn, 0))
            seen.add(sn)

    return pairings


def our_pairings_to_set(pairings: List[dict]) -> Set[Tuple[int, int]]:
    """Convert our engine output to a normalized set for comparison."""
    result = set()
    for p in pairings:
        if p.get("bye"):
            result.add((p["white_id"], 0))
        else:
            pair = tuple(sorted([p["white_id"], p["black_id"]]))
            result.add(pair)
    return result


# ---------------------------------------------------------------------------
# Structural validation (does not require matching reference pairings)
# ---------------------------------------------------------------------------

def validate_pairings_structure(
    pairings: List[dict],
    players: List[dict],
    previous_pairings: Set[Tuple[int, int]],
    round_num: int,
    total_rounds: int,
) -> List[str]:
    """
    Validate FIDE structural constraints on pairings.

    Returns list of violation strings (empty = all good).
    """
    violations = []
    regular = [p for p in pairings if not p.get("bye")]
    byes = [p for p in pairings if p.get("bye")]
    pmap = {p["id"]: p for p in players}

    # 1. No repeat pairings
    for p in regular:
        pair = tuple(sorted([p["white_id"], p["black_id"]]))
        if pair in previous_pairings:
            violations.append(f"Repeat pairing: {pair}")

    # 2. Each player appears at most once
    ids_seen = []
    for p in pairings:
        ids_seen.append(p["white_id"])
        if p.get("black_id") is not None:
            ids_seen.append(p["black_id"])
    if len(ids_seen) != len(set(ids_seen)):
        violations.append("Duplicate player in pairings")

    # 3. Table numbers are sequential
    tables = [p["table"] for p in pairings]
    if tables != list(range(1, len(tables) + 1)):
        violations.append(f"Non-sequential tables: {tables}")

    # 4. Color constraints (not last round)
    is_last = round_num >= total_rounds
    if not is_last:
        for p in regular:
            for pid, color in [
                (p["white_id"], "white"),
                (p["black_id"], "black"),
            ]:
                player = pmap.get(pid, {})
                hist = list(player.get("color_hist", []))
                test_hist = hist + [color]
                # No 3-in-a-row
                if len(test_hist) >= 3 and (
                    test_hist[-1] == test_hist[-2] == test_hist[-3]
                ):
                    violations.append(
                        f"3 same colours for player {pid}: {test_hist}"
                    )
                # Color diff ≤ ±2
                new_diff = test_hist.count("white") - test_hist.count("black")
                if abs(new_diff) > 2:
                    violations.append(
                        f"Colour diff {new_diff} for player {pid}"
                    )

    return violations


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------

def _get_fixtures() -> List[Path]:
    """Get all .trf fixture files."""
    if not FIXTURES_DIR.exists():
        return []
    return sorted(FIXTURES_DIR.glob("*.trf"))


# ---------------------------------------------------------------------------
# Test classes
# ---------------------------------------------------------------------------


class TestTRFParser(unittest.TestCase):
    """Verify the TRF parser works correctly on fixture files."""

    def test_parser_reads_all_fixtures(self):
        """Every fixture should parse without errors."""
        for fp in _get_fixtures():
            with self.subTest(file=fp.name):
                data = parse_trf(fp)
                self.assertGreater(data["total_rounds"], 0, f"{fp.name}: no rounds")
                self.assertGreater(len(data["players"]), 0, f"{fp.name}: no players")

    def test_parser_player_count_matches(self):
        """The number of parsed 001 lines should match the header."""
        for fp in _get_fixtures():
            with self.subTest(file=fp.name):
                data = parse_trf(fp)
                self.assertEqual(
                    len(data["players"]),
                    data["num_players"],
                    f"{fp.name}: player count mismatch",
                )

    def test_parser_round_count(self):
        """Each player should have total_rounds entries."""
        for fp in _get_fixtures():
            with self.subTest(file=fp.name):
                data = parse_trf(fp)
                for p in data["players"]:
                    self.assertEqual(
                        len(p["rounds"]),
                        data["total_rounds"],
                        f"{fp.name}: player {p['starting_number']} "
                        f"has {len(p['rounds'])} rounds, expected {data['total_rounds']}",
                    )


class TestRound1Deterministic(unittest.TestCase):
    """
    Round 1 is fully deterministic in Dutch: top-half vs bottom-half.
    Our engine's round 1 should always match the reference TRF.
    """

    def test_round1_matches_all_fixtures(self):
        """Round 1 pairings should match the TRF for every fixture."""
        for fp in _get_fixtures():
            with self.subTest(file=fp.name):
                data = parse_trf(fp)

                # Build initial state (no prior rounds)
                players, prev, rnd = build_round_state(data, 0)

                # Filter out players unavailable in round 1
                # (voluntary byes, zero-point byes, absences)
                unavailable = get_unavailable_players(data, 1)
                active_players = [
                    p for p in players if p["id"] not in unavailable
                ]

                expected = extract_round_pairings(data, 1)

                if not expected:
                    continue  # Skip if no extractable pairings

                our = dutch_pairings(
                    active_players, prev, rnd, data["total_rounds"]
                )
                our_set = our_pairings_to_set(our)

                # Compare actual game pairings only (not bye assignment details)
                our_games = {p for p in our_set if p[1] != 0}
                expected_games = {p for p in expected if p[1] != 0}

                self.assertEqual(
                    our_games,
                    expected_games,
                    f"{fp.name} R1: ours={sorted(our_games)} expected={sorted(expected_games)}",
                )


class TestStructuralValidation(unittest.TestCase):
    """
    For every round of every fixture, validate that our engine's pairings
    satisfy all FIDE structural constraints (no repeats, colour rules, etc.),
    even if they don't exactly match the reference pairings.
    """

    def test_no_violations_all_fixtures(self):
        """Our engine should produce structurally valid pairings for all rounds."""
        for fp in _get_fixtures():
            with self.subTest(file=fp.name):
                data = parse_trf(fp)
                total_rounds = data["total_rounds"]

                # Only test the first few rounds to avoid slow tests on 31+ round files
                rounds_to_test = min(total_rounds, 9)

                for rnd in range(1, rounds_to_test + 1):
                    players, prev, next_rnd = build_round_state(data, rnd - 1)

                    # Filter out players who have a bye/absent result for all
                    # remaining rounds (withdrawn players)
                    active_players = []
                    for p in players:
                        trf_p = next(
                            (tp for tp in data["players"]
                             if tp["starting_number"] == p["id"]),
                            None,
                        )
                        if trf_p and rnd - 1 < len(trf_p["rounds"]):
                            active_players.append(p)

                    if len(active_players) < 2:
                        continue

                    our = dutch_pairings(
                        active_players, prev, next_rnd, total_rounds,
                    )

                    violations = validate_pairings_structure(
                        our, active_players, prev, next_rnd, total_rounds,
                    )

                    self.assertEqual(
                        len(violations), 0,
                        f"{fp.name} R{rnd}: {violations}",
                    )


class TestSmallTournaments(unittest.TestCase):
    """Focused tests on small (7-player) tournaments — rich in bye edge cases."""

    def _run_small_tournament(self, filename: str):
        fp = FIXTURES_DIR / filename
        if not fp.exists():
            self.skipTest(f"{filename} not found")

        data = parse_trf(fp)
        total_rounds = data["total_rounds"]

        all_match = True
        mismatches = []

        for rnd in range(1, total_rounds + 1):
            players, prev, next_rnd = build_round_state(data, rnd - 1)
            expected = extract_round_pairings(data, rnd)

            if not expected:
                continue

            our = dutch_pairings(players, prev, next_rnd, total_rounds)
            our_set = our_pairings_to_set(our)

            # Compare game pairings (ignore bye player identity for now)
            our_games = {p for p in our_set if p[1] != 0}
            expected_games = {p for p in expected if p[1] != 0}

            if our_games != expected_games:
                all_match = False
                mismatches.append(
                    f"R{rnd}: ours={sorted(our_games)} ref={sorted(expected_games)}"
                )

            # Always validate structure
            violations = validate_pairings_structure(
                our, players, prev, next_rnd, total_rounds,
            )
            self.assertEqual(
                len(violations), 0,
                f"{filename} R{rnd}: {violations}",
            )

        # Report mismatches (informational, not failure — our engine may
        # make different but equally valid choices in later rounds)
        if mismatches:
            print(f"\n  {filename} mismatches ({len(mismatches)}/{total_rounds}):")
            for m in mismatches:
                print(f"    {m}")

    def test_small_clean(self):
        self._run_small_tournament("small_7p5r_clean.trf")

    def test_small_byes(self):
        self._run_small_tournament("small_7p5r_byes.trf")

    def test_small_varied(self):
        self._run_small_tournament("small_7p5r_varied.trf")


class TestMediumTournaments(unittest.TestCase):
    """Tests on 9-15 player tournaments."""

    def _run_tournament_structural(self, filename: str, max_rounds: int = 9):
        fp = FIXTURES_DIR / filename
        if not fp.exists():
            self.skipTest(f"{filename} not found")

        data = parse_trf(fp)
        total_rounds = data["total_rounds"]
        rounds_to_test = min(total_rounds, max_rounds)

        for rnd in range(1, rounds_to_test + 1):
            players, prev, next_rnd = build_round_state(data, rnd - 1)

            our = dutch_pairings(players, prev, next_rnd, total_rounds)

            violations = validate_pairings_structure(
                our, players, prev, next_rnd, total_rounds,
            )
            self.assertEqual(
                len(violations), 0,
                f"{filename} R{rnd}: {violations}",
            )

            # Verify all active players are paired
            active_ids = {p["id"] for p in players}
            paired_ids = set()
            for p in our:
                paired_ids.add(p["white_id"])
                if p.get("black_id") is not None:
                    paired_ids.add(p["black_id"])
            self.assertEqual(
                paired_ids, active_ids,
                f"{filename} R{rnd}: not all players paired",
            )

    def test_9p7r_clean(self):
        self._run_tournament_structural("medium_9p7r_clean.trf", 7)

    def test_9p7r_forfeits(self):
        self._run_tournament_structural("medium_9p7r_forfeits.trf", 7)

    def test_15p9r_byes(self):
        self._run_tournament_structural("large_15p9r_byes.trf", 9)

    def test_15p9r_mixed(self):
        self._run_tournament_structural("large_15p9r_mixed.trf", 9)

    def test_15p9r_spread(self):
        self._run_tournament_structural("large_15p9r_spread.trf", 9)


class TestLargeTournaments(unittest.TestCase):
    """Tests on 30-50 player tournaments (stress testing)."""

    def _run_tournament_structural(self, filename: str, max_rounds: int = 9):
        fp = FIXTURES_DIR / filename
        if not fp.exists():
            self.skipTest(f"{filename} not found")

        data = parse_trf(fp)
        total_rounds = data["total_rounds"]
        rounds_to_test = min(total_rounds, max_rounds)

        for rnd in range(1, rounds_to_test + 1):
            players, prev, next_rnd = build_round_state(data, rnd - 1)

            our = dutch_pairings(players, prev, next_rnd, total_rounds)

            violations = validate_pairings_structure(
                our, players, prev, next_rnd, total_rounds,
            )
            self.assertEqual(
                len(violations), 0,
                f"{filename} R{rnd}: {violations}",
            )

    def test_30p11r_even(self):
        self._run_tournament_structural("big_30p11r_even.trf", 9)

    def test_30p11r_varied(self):
        self._run_tournament_structural("big_30p11r_varied.trf", 9)

    def test_50p15r_stress(self):
        self._run_tournament_structural("stress_50p15r.trf", 7)

    def test_50p31r_manybyes(self):
        """50 players, 31 rounds with high bye/forfeit rates."""
        self._run_tournament_structural("stress_50p31r_manybyes.trf", 5)


class TestMiscEdgeCases(unittest.TestCase):
    """Tests on misc edge case tournaments."""

    def _run_structural(self, filename: str, max_rounds: int = 5):
        fp = FIXTURES_DIR / filename
        if not fp.exists():
            self.skipTest(f"{filename} not found")

        data = parse_trf(fp)
        total_rounds = data["total_rounds"]
        rounds_to_test = min(total_rounds, max_rounds)

        for rnd in range(1, rounds_to_test + 1):
            players, prev, next_rnd = build_round_state(data, rnd - 1)

            our = dutch_pairings(players, prev, next_rnd, total_rounds)

            violations = validate_pairings_structure(
                our, players, prev, next_rnd, total_rounds,
            )
            self.assertEqual(
                len(violations), 0,
                f"{filename} R{rnd}: {violations}",
            )

    def test_misc_edge_case_1(self):
        self._run_structural("misc_edge_case_1.trf")

    def test_misc_edge_case_2(self):
        self._run_structural("misc_edge_case_2.trf")

    def test_misc_edge_case_3(self):
        self._run_structural("misc_edge_case_3.trf")


class TestByeAssignmentFromTRF(unittest.TestCase):
    """
    Validate bye assignment in odd-player tournaments from TRF data.
    Ensures every odd-count round produces exactly one bye, and that
    the bye recipient follows FIDE rules.
    """

    def test_odd_player_bye_consistency(self):
        """For odd-player fixtures, verify bye assignment every round."""
        odd_fixtures = [
            "small_7p5r_clean.trf",
            "small_7p5r_byes.trf",
            "small_7p5r_varied.trf",
            "medium_9p7r_clean.trf",
            "medium_9p7r_forfeits.trf",
            "large_15p9r_byes.trf",
            "large_15p9r_mixed.trf",
            "large_15p9r_spread.trf",
        ]
        for filename in odd_fixtures:
            fp = FIXTURES_DIR / filename
            if not fp.exists():
                continue

            with self.subTest(file=filename):
                data = parse_trf(fp)
                num_players = data["num_players"]

                if num_players % 2 == 0:
                    continue  # Only test odd-count tournaments

                total_rounds = data["total_rounds"]
                rounds_to_test = min(total_rounds, 5)

                for rnd in range(1, rounds_to_test + 1):
                    players, prev, next_rnd = build_round_state(data, rnd - 1)

                    our = dutch_pairings(
                        players, prev, next_rnd, total_rounds,
                    )

                    byes = [p for p in our if p.get("bye")]
                    regular = [p for p in our if not p.get("bye")]

                    self.assertEqual(
                        len(byes), 1,
                        f"{filename} R{rnd}: expected 1 bye, got {len(byes)}",
                    )
                    expected_games = (num_players - 1) // 2
                    self.assertEqual(
                        len(regular), expected_games,
                        f"{filename} R{rnd}: expected {expected_games} games",
                    )


if __name__ == "__main__":
    unittest.main(verbosity=2)
